#!/bin/sh

source ./porousGasificationMediaDirectories

cd $FOAM_HGS/porousReactingMedia
wclean libso

cd $FOAM_HGS/thermophysicalModels
./Allwclean

cd $FOAM_HGS/pyrolysisModels
wclean libso

cd $WM_PROJECT_USER_DIR/applications/porousGasificationFoam
wclean

cd $WM_PROJECT_USER_DIR/applications/dummyPressurePorousGasificationFoam
wclean

cd $WM_PROJECT_USER_DIR/applications/totalMassPorousGasificationFoam
wclean
